# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - ">0.2%"
  - "last 2 versions"
  - "Firefox ESR"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "dist/**/*.{html,php,htm}"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*
    - .reveal-overlay
    - body.is-reveal-open
    - .tooltip
    - .phone-tooltip
    - .is-off-canvas-open
    - .js-off-canvas-exit
    - .js-off-canvas-overlay
    - .off-canvas.is-open
    - .js-off-canvas-overlay.is-overlay-fixed
    - .js-off-canvas-overlay.is-closable
    - .js-off-canvas-overlay.is-visible
    - .js-off-canvas-overlay
    - .off-canvas-content.has-transition-push
    - .off-canvas-content.is-open-right.has-transition-push

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "assets/.htaccess" # <- specify import invisible file .htaccess
    - "assets/**" # <- import all files inside assets/
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/foundation-sites/scss"
    - "bower_components/motion-ui/src"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries requried by Foundation
    # - "bower_components/jquery/dist/jquery.js" # <- alternatively utilize Google jQuery CDN
    - "bower_components/what-input/dist/what-input.js"
    # Core Foundation files
    - "bower_components/foundation-sites/dist/js/plugins/foundation.core.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.util.*.js"

    # Individual util files
    - "bower_components/foundation-sites/dist/js/plugins/foundation.util.box.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.util.keyboard.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.util.mediaQuery.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.util.imageLoader.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.util.motion.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.util.nest.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.util.timer.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.util.touch.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.util.triggers.js"

    # Individual Foundation components
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.abide.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.accordion.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.accordionMenu.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.drilldown.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.dropdown.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.dropdownMenu.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.equalizer.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.interchange.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.smoothScroll.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.magellan.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.offcanvas.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.orbit.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.responsiveAccordionTabs.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.responsiveMenu.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.responsiveToggle.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.reveal.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.slider.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.sticky.js"
    # - "bower_components/foundation-sites/dist/js/plugins/foundation.tabs.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.toggler.js"
    - "bower_components/foundation-sites/dist/js/plugins/foundation.tooltip.js"

    # Main JS file (imports everything above)
    - "js/app-min.js"
